### ISSUE TITLE
More details ?

### ISSUE THREAD

**Issue by hmyh1202** [tushiqi/Identifying_PMDs#1]
Can you give us more detail about the PMD method ?
Thank you !

**Comment by tushiqi** [comment]
Sorry, but the program has not been finished yet.
For a systematic genome wide identification of PMDs, I recommend using MethPipe, which is developed by the Smith lab.
See http://smithlabresearch.org/software/methpipe/ for details.

**Comment by tushiqi** [comment]
> Can you give us more detail about the PMD method ?
> Thank you !

Sorry, but the program has not been finished yet.
For a systematic genome wide identification of PMDs, I recommend using MethPipe, which is developed by the Smith lab.
See http://smithlabresearch.org/software/methpipe/ for details.

**Comment by hmyh1202** [comment]
So does Smith lab niubility ?

**Comment by tushiqi** [comment]
> So does Smith lab niubility ?

Yes. I am quite sure.
